### ISSUE TITLE
[1.14.4-0.1.2] crashes dedicated server with unsatisfiedlink error

### ISSUE THREAD

**Issue by kreezxil** [coolsimulations/SurvivalPlus-Lightsabers#1] opened 2019-11-11 23:08 UTC
report name | paste
 ----------- | -----
crash-2019-11-11_17.59.18-server.txt | http://paste.ubuntu.com/p/hZ552vhZxm/
crash-2019-11-11_18.02.51-server.txt | http://paste.ubuntu.com/p/rVb3pgbPPK/

**Comment by coolsimulations** [comment] 2019-11-18 05:27
Didn't see this until just now. The issue is because I've made it so that when you login to a world it plays a sound "Hello There". It's been tested and works on MacOS and Windows 10 but I didn't realise it didn't work on Linux. Thanks for reporting, I will look into resolving this issue.

**Comment by coolsimulations** [comment] 2020-01-05 06:40
Fixed with version 0.1.3 cba59325ce8338a809340645fab91b1a364c6d90 by making the sound client side as well as adding a config option in [SurvivalPlus](https://github.com/coolsimulations/SurvivalPlus/commit/95defd138061b2c28379e10dfd653f1891c3d1dc).

**Closed as completed by coolsimulations** 2020-01-05 06:40 UTC

**Comment by coolsimulations** [comment] 2021-08-01 01:23
Permanently fixed with https://github.com/coolsimulations/SurvivalPlus-Lightsabers/commit/eb831392fb7a253bff2ddf5cb85499d112f33ed0. Turns out this crash occurs due to the java dependency sun.audio not being included in most java forks such as OpenJDK.
